---
- name: Deploy static server environment
  hosts: test_servers
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - users
    - ssh
    - packages
    - zsh
    - static
    - nginx
  post_tasks:
    - name: Display deployment summary
      debug:
        msg: |
          Deployment completed successfully!
          - SSH is configured and running on port 2222
          - Nginx is running on port 80
          - Static files are available at http://localhost/images/
